@baseurl=http://localhost/api/

# @name login
POST {{baseurl}}auth/login
Content-Type: application/json

{
    "email" : "edmund19@example.com",
    "password" : "password"
}

###
@authToken = {{login.response.body.access_token}}

# @name createComment
POST {{baseurl}}auth/logout
Authorization: Bearer {{authToken}}

